USE mvsr_alumni;
ALTER TABLE events
  ADD COLUMN end_time VARCHAR(50) DEFAULT NULL,
  ADD COLUMN type VARCHAR(50) DEFAULT 'offline',
  ADD COLUMN status VARCHAR(50) DEFAULT 'upcoming',
  ADD COLUMN attendees JSON DEFAULT NULL,
  ADD COLUMN max_attendees INT DEFAULT 100,
  ADD COLUMN current_attendees INT DEFAULT 0,
  ADD COLUMN tags JSON DEFAULT NULL,
  ADD COLUMN is_featured BOOLEAN DEFAULT FALSE,
  ADD COLUMN is_public BOOLEAN DEFAULT TRUE,
  ADD COLUMN registration_deadline TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN created_by INT DEFAULT NULL;
